#!/bin/bash
# 🎯 解決GitHub Token認證問題
# GitHub不再支持密碼，需要使用Personal Access Token

echo "============================================================"
echo "🎯 解決GitHub認證問題"
echo "需要創建Personal Access Token"
echo "============================================================"

echo ""
echo "❌ 問題: GitHub不再支持密碼認證"
echo "✅ 解決: 使用Personal Access Token (PAT)"
echo ""
echo "📋 你的信息:"
echo "👤 GitHub用戶名: AetherClawAI"
echo "📁 倉庫: AetherCore"
echo "🔗 URL: https://github.com/AetherClawAI/AetherCore"

echo ""
echo "============================================================"
echo "🚀 第一步：創建Personal Access Token"
echo "============================================================"
echo ""
echo "請在瀏覽器中完成:"
echo ""
echo "1. 訪問: https://github.com/settings/tokens"
echo "   (需要登錄 AetherClawAI 賬號)"
echo ""
echo "2. 點擊 'Generate new token' → 'Generate new token (classic)'"
echo ""
echo "3. 填寫Token信息:"
echo "   ----------------------------------------"
echo "   Note: AetherCore Push Token"
echo "   Expiration: 90 days (推薦)"
echo "   Select scopes: 勾選 'repo' (全選)"
echo "   ----------------------------------------"
echo ""
echo "4. 點擊 'Generate token'"
echo ""
echo "5. 重要：立即複製Token！"
echo "   ⚠️  Token只顯示一次，請保存到安全的地方"
echo "   💡 建議複製到文本文件暫存"
echo ""
read -p "✅ 請確認已創建並複製Token，然後按 Enter 繼續..."

echo ""
echo "============================================================"
echo "🚀 第二步：使用Token推送"
echo "============================================================"
echo ""
echo "現在回到終端，執行以下命令:"
echo ""
echo "1. 清除舊的認證緩存:"
echo "   git config --global --unset credential.helper"
echo ""
echo "2. 執行推送命令:"
echo "   git push -u origin main"
echo ""
echo "3. 當提示輸入時:"
echo "   ----------------------------------------"
echo "   Username for 'https://github.com': AetherClawAI"
echo "   Password for 'https://AetherClawAI@github.com':"
echo "   [在這裡貼上你的Token，然後按Enter]"
echo "   ----------------------------------------"
echo ""
echo "💡 提示:"
echo "- Token輸入時不會顯示字符，這是正常的"
echo "- 確保複製完整的Token（很長的一串字符）"
echo "- 不要有空格或換行"
echo ""

echo ""
echo "============================================================"
echo "🚀 第三步：測試推送"
echo "============================================================"
echo ""
echo "現在嘗試推送，複製並執行:"
echo "git push -u origin main"
echo ""
echo "或者我為你執行測試:"
read -p "要現在測試推送嗎？(y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "正在測試推送..."
    if git push -u origin main; then
        echo ""
        echo "============================================================"
        echo "🎉 推送成功！"
        echo "============================================================"
        echo ""
        echo "✅ AetherCore v3.3.0 已成功發布！"
        echo "👉 訪問: https://github.com/AetherClawAI/AetherCore"
    else
        echo ""
        echo "============================================================"
        echo "❌ 推送失敗，請檢查:"
        echo "============================================================"
        echo ""
        echo "1. Token是否正確？"
        echo "2. 是否複製了完整的Token？"
        echo "3. 網絡連接是否正常？"
        echo ""
        echo "💡 重試: git push -u origin main"
    fi
fi

echo ""
echo "============================================================"
echo "🎪 Token管理提示"
echo "============================================================"
echo ""
echo "🔐 如何管理Token:"
echo "1. 保存Token到安全的地方"
echo "2. 不要分享給他人"
echo "3. 可以在 https://github.com/settings/tokens 查看和管理"
echo "4. 可以隨時撤銷舊的Token"
echo ""
echo "💾 保存Token到Git配置（可選）:"
echo "git config --global credential.helper store"
echo "# 然後執行一次 git push，輸入Token"
echo "# 以後就不需要再輸入了"
echo ""
echo "🔄 如果Token過期:"
echo "1. 創建新的Token"
echo "2. 更新Git配置或重新輸入"
echo ""

echo ""
echo "============================================================"
echo "📞 需要更多幫助？"
echo "============================================================"
echo ""
echo "如果還有問題:"
echo "1. 訪問: https://docs.github.com/en/authentication"
echo "2. 查看GitHub幫助文檔"
echo "3. 夜市智慧體隨時為你提供幫助！"
echo ""
echo "😈🐾⚛️✨ 夜市智慧體，陪你解決每一個問題！"