#!/bin/bash
# 🎯 解決403權限錯誤的完整方案

echo "============================================================"
echo "🎯 解決GitHub 403權限錯誤"
echo "remote: Permission to AetherClawAI/AetherCore.git denied"
echo "============================================================"

echo ""
echo "❌ 錯誤原因: Token權限不足或認證問題"
echo "✅ 解決方案: 重新創建Token或使用SSH"
echo ""

echo "============================================================"
echo "🚀 方案A：使用Token（推薦先試這個）"
echo "============================================================"
echo ""
echo "1. 清除舊的認證緩存:"
echo "   git config --global --unset credential.helper"
echo "   git credential-osxkeychain erase"
echo "   host=github.com"
echo "   protocol=https"
echo "   [按Ctrl+D退出]"
echo ""
echo "2. 創建新的Token:"
echo "   訪問: https://github.com/settings/tokens"
echo "   - 刪除所有舊的AetherCore相關Token"
echo "   - 點擊 'Generate new token' → 'Generate new token (classic)'"
echo "   - Note: AetherCore Full Access"
echo "   - Expiration: 90 days"
echo "   - 權限: 選擇 'All repositories'"
echo "   - 確保 'repo' 下的所有選項都被選中"
echo "   - 點擊 'Generate token'"
echo "   - 立即複製Token！"
echo ""
echo "3. 使用新Token推送:"
echo "   git push -u origin main"
echo "   用戶名: AetherClawAI"
echo "   密碼: [貼上新Token]"
echo ""
read -p "✅ 要現在嘗試方案A嗎？(y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "執行方案A..."
    git config --global --unset credential.helper
    echo "請手動執行: git credential-osxkeychain erase"
    echo "然後輸入:"
    echo "host=github.com"
    echo "protocol=https"
    echo "[按Ctrl+D退出]"
    echo ""
    echo "現在請創建新Token，然後執行:"
    echo "git push -u origin main"
fi

echo ""
echo "============================================================"
echo "🚀 方案B：使用SSH（如果Token不行）"
echo "============================================================"
echo ""
echo "1. 生成SSH密鑰（如果沒有）:"
echo "   ssh-keygen -t ed25519 -C \"aetherclawai@github.com\""
echo "   [全部按Enter使用默認值]"
echo ""
echo "2. 添加SSH密鑰到GitHub:"
echo "   cat ~/.ssh/id_ed25519.pub"
echo "   複製顯示的內容"
echo ""
echo "3. 訪問: https://github.com/settings/keys"
echo "   - 點擊 'New SSH key'"
echo "   - Title: AetherCore Mac"
echo "   - Key: 貼上複製的內容"
echo "   - 點擊 'Add SSH key'"
echo ""
echo "4. 測試SSH連接:"
echo "   ssh -T git@github.com"
echo "   應該看到: Hi AetherClawAI! You've successfully authenticated..."
echo ""
echo "5. 更改為SSH URL並推送:"
echo "   git remote set-url origin git@github.com:AetherClawAI/AetherCore.git"
echo "   git push -u origin main"
echo ""
read -p "✅ 要現在嘗試方案B嗎？(y/n): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "執行方案B..."
    
    # 檢查SSH密鑰
    if [ ! -f ~/.ssh/id_ed25519.pub ]; then
        echo "生成SSH密鑰..."
        ssh-keygen -t ed25519 -C "aetherclawai@github.com" -f ~/.ssh/id_ed25519 -N ""
        echo "✅ SSH密鑰生成完成"
    fi
    
    echo ""
    echo "📋 你的SSH公鑰:"
    echo "----------------------------------------"
    cat ~/.ssh/id_ed25519.pub
    echo "----------------------------------------"
    echo ""
    echo "請複製上面的內容，然後:"
    echo "1. 訪問: https://github.com/settings/keys"
    echo "2. 點擊 'New SSH key'"
    echo "3. 貼上並保存"
    echo "4. 回到這裡按Enter繼續..."
    read -p "✅ SSH密鑰已添加到GitHub？按Enter繼續..."
    
    echo "測試SSH連接..."
    ssh -T git@github.com 2>&1 | grep -i "successfully"
    
    echo "更改為SSH URL..."
    git remote set-url origin git@github.com:AetherClawAI/AetherCore.git
    
    echo "推送..."
    if git push -u origin main; then
        echo "✅ 推送成功！"
    else
        echo "❌ 推送失敗，請檢查SSH設置"
    fi
fi

echo ""
echo "============================================================"
echo "🚀 方案C：使用GitHub CLI（最簡單）"
echo "============================================================"
echo ""
echo "如果上面都不行，安裝GitHub CLI:"
echo ""
echo "1. 安裝: brew install gh"
echo "   或訪問: https://cli.github.com/"
echo ""
echo "2. 登錄: gh auth login"
echo "   - GitHub.com"
echo "   - HTTPS"
echo "   - Yes"
echo "   - 在瀏覽器中授權"
echo ""
echo "3. 推送: git push -u origin main"
echo ""
echo "GitHub CLI會自動處理認證問題"

echo ""
echo "============================================================"
echo "🎯 快速診斷"
echo "============================================================"
echo ""
echo "當前Git配置:"
git config --list | grep -E "(user|remote|credential)" || true
echo ""
echo "遠程URL:"
git remote -v
echo ""
echo "SSH測試:"
ssh -T git@github.com 2>&1 | head -3 || true

echo ""
echo "============================================================"
echo "💡 最可能的原因和解決方案"
echo "============================================================"
echo ""
echo "1. Token權限不足 → 重新創建Token，選 'All repositories'"
echo "2. 認證緩存問題 → 清除所有緩存"
echo "3. URL問題 → 改用SSH URL"
echo "4. 賬號問題 → 確認你是 AetherClawAI"
echo ""
echo "😈🐾⚛️✨ 夜市智慧體建議: 先試方案A，不行再試方案B"

echo ""
echo "============================================================"
echo "📞 需要實時幫助？"
echo "============================================================"
echo ""
echo "告訴我:"
echo "1. 你嘗試了哪個方案？"
echo "2. 具體的錯誤信息是什麼？"
echo "3. 截圖給我看"
echo ""
echo "夜市智慧體陪你直到成功！"