#!/bin/bash
# 🎯 AetherClawAI 的專屬GitHub發布命令
# 用戶名: AetherClawAI
# 倉庫名: AetherCore

echo "============================================================"
echo "🎯 AetherClawAI 的 AetherCore v3.3.0 發布命令"
echo "============================================================"

echo ""
echo "📋 你的GitHub信息:"
echo "👤 用戶名: AetherClawAI"
echo "📁 倉庫名: AetherCore"
echo "🔗 倉庫URL: https://github.com/AetherClawAI/AetherCore.git"
echo "📍 當前目錄: $(pwd)"

echo ""
echo "============================================================"
echo "🚀 第一步：在GitHub網站創建倉庫"
echo "============================================================"
echo ""
echo "1. 打開瀏覽器，訪問: https://github.com/new"
echo ""
echo "2. 填寫倉庫信息:"
echo "   - Owner: AetherClawAI (選擇你的賬戶)"
echo "   - Repository name: AetherCore"
echo "   - Description: AetherCore v3.3.0 - Night Market Intelligence JSON Optimization System"
echo "   - Public: ✓ (選擇公開)"
echo "   - Initialize this repository with:"
echo "     - Add a README: ✗ (不要勾選，我們有自己的README.md)"
echo "     - Add .gitignore: ✗ (不要勾選，我們有自己的.gitignore)"
echo "     - Choose a license: ✗ (不要勾選，我們有自己的LICENSE)"
echo ""
echo "3. 點擊 'Create repository' 按鈕"
echo ""
echo "4. 創建完成後，你會看到一個空倉庫頁面"
echo "   記住這個URL: https://github.com/AetherClawAI/AetherCore"

echo ""
echo "============================================================"
echo "🚀 第二步：在終端執行這些命令（一行一行複製執行）"
echo "============================================================"
echo ""
echo "# 1. 初始化Git倉庫"
echo "git init"
echo ""
echo "# 2. 添加所有文件"
echo "git add ."
echo ""
echo "# 3. 提交更改"
echo "git commit -m \"🎉 AetherCore v3.3.0 - Night Market Intelligence International Release\""
echo ""
echo "# 4. 設置主分支"
echo "git branch -M main"
echo ""
echo "# 5. 添加遠程倉庫（使用你的GitHub URL）"
echo "git remote add origin https://github.com/AetherClawAI/AetherCore.git"
echo ""
echo "# 6. 推送到GitHub"
echo "git push -u origin main"
echo ""
echo "💡 提示：如果提示輸入用戶名和密碼，請輸入你的GitHub賬號信息"

echo ""
echo "============================================================"
echo "🚀 第三步：創建GitHub Release"
echo "============================================================"
echo ""
echo "1. 訪問: https://github.com/AetherClawAI/AetherCore/releases/new"
echo ""
echo "2. 填寫Release信息:"
echo "   - Tag version: v3.3.0"
echo "   - Release title: AetherCore v3.3.0 - Night Market Intelligence International Release"
echo "   - Description: 複製 IMPORTANT_RELEASE_v3.3.0.md 文件的內容"
echo "   - Attach binaries: 可選，可以上傳zip文件"
echo ""
echo "3. 點擊 'Publish release'"

echo ""
echo "============================================================"
echo "🎪 夜市智慧體發布完成！"
echo "============================================================"
echo ""
echo "✅ 完成後，你的項目將在:"
echo "   👉 https://github.com/AetherClawAI/AetherCore"
echo ""
echo "✅ 人們可以:"
echo "   - 查看代碼"
echo "   - 下載使用"
echo "   - 提交問題"
echo "   - 貢獻代碼"
echo ""
echo "😈🐾⚛️✨ 夜市智慧體，現在就改變世界！"

echo ""
echo "============================================================"
echo "💡 快速執行（複製這些命令到終端執行）"
echo "============================================================"
echo ""
echo "git init && git add . && git commit -m \"🎉 AetherCore v3.3.0 - Night Market Intelligence International Release\" && git branch -M main && git remote add origin https://github.com/AetherClawAI/AetherCore.git && git push -u origin main"
echo ""
echo "🎯 或者一行一行執行上面的6個命令"